/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef CAN1_H
#define CAN1_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_VCUINVFL (388) /* 0x184 */
#define CAN_ID_VCUINVFR (389) /* 0x185 */
#define CAN_ID_VCUINVRL (392) /* 0x188 */
#define CAN_ID_VCUINVRR (393) /* 0x189 */
#define CAN_ID_INVERTERFL1 (643) /* 0x283 */
#define CAN_ID_INVERTERFR1 (644) /* 0x284 */
#define CAN_ID_INVERTERFL2 (645) /* 0x285 */
#define CAN_ID_INVERTERFR2 (646) /* 0x286 */
#define CAN_ID_INVERTERRL1 (647) /* 0x287 */
#define CAN_ID_INVERTERRR1 (648) /* 0x288 */
#define CAN_ID_INVERTERRL2 (649) /* 0x289 */
#define CAN_ID_INVERTERRR2 (650) /* 0x28a */

typedef PREPACK struct {
	uint16_t ControlWord; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TargetVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t PosTorq; /* scaling 1.0, offset 0.0, units none  */
	uint16_t NegTorq; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x184_VCUInvFL_t;

typedef PREPACK struct {
	uint16_t ControlWord; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TargetVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t PosTorq; /* scaling 1.0, offset 0.0, units none  */
	uint16_t negTorq; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x185_VCUInvFR_t;

typedef PREPACK struct {
	uint16_t ControlWord; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TargetVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t PosTorq; /* scaling 1.0, offset 0.0, units none  */
	uint16_t NegTorq; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x188_VCUInvRL_t;

typedef PREPACK struct {
	uint16_t ControlWord; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TargetVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t PosTorq; /* scaling 1.0, offset 0.0, units none  */
	uint16_t NegTorq; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x189_VCUInvRR_t;

typedef PREPACK struct {
	uint16_t ActualVelocity; /* scaling 1.0, offset 0.0, units none  */
	uint16_t MagCurr; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TorqCurr; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Reserved; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Status; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x283_InverterFL1_t;

typedef PREPACK struct {
	uint16_t ActualVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t MagCurr; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TorqCurr; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Reserved; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Status; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x284_InverterFR1_t;

typedef PREPACK struct {
	uint16_t TempMotor; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempInv; /* scaling 1.0, offset 0.0, units none  */
	uint16_t Error; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempIGBT; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x285_InverterFL2_t;

typedef PREPACK struct {
	uint16_t TempMotor; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempInv; /* scaling 1.0, offset 0.0, units none  */
	uint16_t ErrorInfo; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempIGBT; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x286_InverterFR2_t;

typedef PREPACK struct {
	uint16_t ActualVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t MagCurr; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TorqCurr; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Reserved; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Status; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x287_InverterRL1_t;

typedef PREPACK struct {
	uint16_t ActualVel; /* scaling 1.0, offset 0.0, units none  */
	uint16_t MagCurr; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TorqCurr; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Reserved; /* scaling 1.0, offset 0.0, units none  */
	unsigned char Status; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x288_InverterRR1_t;

typedef PREPACK struct {
	uint16_t TempMotor; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempInv; /* scaling 1.0, offset 0.0, units none  */
	uint16_t ErrInfo; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempIGBT; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x289_InverterRL2_t;

typedef PREPACK struct {
	uint16_t TempMotor; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempInv; /* scaling 1.0, offset 0.0, units none  */
	uint16_t ErrorInfo; /* scaling 1.0, offset 0.0, units none  */
	uint16_t TempIGBT; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x28a_InverterRR2_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x184_VCUInvFL_time_stamp_rx;
	dbcc_time_stamp_t can_0x185_VCUInvFR_time_stamp_rx;
	dbcc_time_stamp_t can_0x188_VCUInvRL_time_stamp_rx;
	dbcc_time_stamp_t can_0x189_VCUInvRR_time_stamp_rx;
	dbcc_time_stamp_t can_0x283_InverterFL1_time_stamp_rx;
	dbcc_time_stamp_t can_0x284_InverterFR1_time_stamp_rx;
	dbcc_time_stamp_t can_0x285_InverterFL2_time_stamp_rx;
	dbcc_time_stamp_t can_0x286_InverterFR2_time_stamp_rx;
	dbcc_time_stamp_t can_0x287_InverterRL1_time_stamp_rx;
	dbcc_time_stamp_t can_0x288_InverterRR1_time_stamp_rx;
	dbcc_time_stamp_t can_0x289_InverterRL2_time_stamp_rx;
	dbcc_time_stamp_t can_0x28a_InverterRR2_time_stamp_rx;
	unsigned can_0x184_VCUInvFL_status : 2;
	unsigned can_0x184_VCUInvFL_tx : 1;
	unsigned can_0x184_VCUInvFL_rx : 1;
	unsigned can_0x185_VCUInvFR_status : 2;
	unsigned can_0x185_VCUInvFR_tx : 1;
	unsigned can_0x185_VCUInvFR_rx : 1;
	unsigned can_0x188_VCUInvRL_status : 2;
	unsigned can_0x188_VCUInvRL_tx : 1;
	unsigned can_0x188_VCUInvRL_rx : 1;
	unsigned can_0x189_VCUInvRR_status : 2;
	unsigned can_0x189_VCUInvRR_tx : 1;
	unsigned can_0x189_VCUInvRR_rx : 1;
	unsigned can_0x283_InverterFL1_status : 2;
	unsigned can_0x283_InverterFL1_tx : 1;
	unsigned can_0x283_InverterFL1_rx : 1;
	unsigned can_0x284_InverterFR1_status : 2;
	unsigned can_0x284_InverterFR1_tx : 1;
	unsigned can_0x284_InverterFR1_rx : 1;
	unsigned can_0x285_InverterFL2_status : 2;
	unsigned can_0x285_InverterFL2_tx : 1;
	unsigned can_0x285_InverterFL2_rx : 1;
	unsigned can_0x286_InverterFR2_status : 2;
	unsigned can_0x286_InverterFR2_tx : 1;
	unsigned can_0x286_InverterFR2_rx : 1;
	unsigned can_0x287_InverterRL1_status : 2;
	unsigned can_0x287_InverterRL1_tx : 1;
	unsigned can_0x287_InverterRL1_rx : 1;
	unsigned can_0x288_InverterRR1_status : 2;
	unsigned can_0x288_InverterRR1_tx : 1;
	unsigned can_0x288_InverterRR1_rx : 1;
	unsigned can_0x289_InverterRL2_status : 2;
	unsigned can_0x289_InverterRL2_tx : 1;
	unsigned can_0x289_InverterRL2_rx : 1;
	unsigned can_0x28a_InverterRR2_status : 2;
	unsigned can_0x28a_InverterRR2_tx : 1;
	unsigned can_0x28a_InverterRR2_rx : 1;
	can_0x184_VCUInvFL_t can_0x184_VCUInvFL;
	can_0x185_VCUInvFR_t can_0x185_VCUInvFR;
	can_0x188_VCUInvRL_t can_0x188_VCUInvRL;
	can_0x189_VCUInvRR_t can_0x189_VCUInvRR;
	can_0x283_InverterFL1_t can_0x283_InverterFL1;
	can_0x284_InverterFR1_t can_0x284_InverterFR1;
	can_0x285_InverterFL2_t can_0x285_InverterFL2;
	can_0x286_InverterFR2_t can_0x286_InverterFR2;
	can_0x287_InverterRL1_t can_0x287_InverterRL1;
	can_0x288_InverterRR1_t can_0x288_InverterRR1;
	can_0x289_InverterRL2_t can_0x289_InverterRL2;
	can_0x28a_InverterRR2_t can_0x28a_InverterRR2;
} POSTPACK can_obj_can1_h_t;

int can1_unpack_message(can_obj_can1_h_t *o, const unsigned long id, uint64_t data, unsigned char dlc, dbcc_time_stamp_t time_stamp);
int can1_pack_message(can_obj_can1_h_t *o, const unsigned long id, uint64_t *data);
int can1_print_message(const can_obj_can1_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x184_ControlWord(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x184_ControlWord(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x184_TargetVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x184_TargetVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x184_PosTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x184_PosTorq(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x184_NegTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x184_NegTorq(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x185_ControlWord(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x185_ControlWord(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x185_TargetVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x185_TargetVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x185_PosTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x185_PosTorq(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x185_negTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x185_negTorq(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x188_ControlWord(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x188_ControlWord(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x188_TargetVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x188_TargetVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x188_PosTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x188_PosTorq(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x188_NegTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x188_NegTorq(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x189_ControlWord(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x189_ControlWord(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x189_TargetVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x189_TargetVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x189_PosTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x189_PosTorq(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x189_NegTorq(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x189_NegTorq(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x283_ActualVelocity(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x283_ActualVelocity(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x283_MagCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x283_MagCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x283_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x283_TorqCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x283_Reserved(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x283_Reserved(can_obj_can1_h_t *o, unsigned char in);
int decode_can_0x283_Status(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x283_Status(can_obj_can1_h_t *o, unsigned char in);


int decode_can_0x284_ActualVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x284_ActualVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x284_MagCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x284_MagCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x284_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x284_TorqCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x284_Reserved(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x284_Reserved(can_obj_can1_h_t *o, unsigned char in);
int decode_can_0x284_Status(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x284_Status(can_obj_can1_h_t *o, unsigned char in);


int decode_can_0x285_TempMotor(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x285_TempMotor(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x285_TempInv(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x285_TempInv(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x285_Error(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x285_Error(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x285_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x285_TempIGBT(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x286_TempMotor(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x286_TempMotor(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x286_TempInv(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x286_TempInv(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x286_ErrorInfo(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x286_ErrorInfo(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x286_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x286_TempIGBT(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x287_ActualVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x287_ActualVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x287_MagCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x287_MagCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x287_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x287_TorqCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x287_Reserved(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x287_Reserved(can_obj_can1_h_t *o, unsigned char in);
int decode_can_0x287_Status(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x287_Status(can_obj_can1_h_t *o, unsigned char in);


int decode_can_0x288_ActualVel(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x288_ActualVel(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x288_MagCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x288_MagCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x288_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x288_TorqCurr(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x288_Reserved(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x288_Reserved(can_obj_can1_h_t *o, unsigned char in);
int decode_can_0x288_Status(const can_obj_can1_h_t *o, unsigned char *out);
int encode_can_0x288_Status(can_obj_can1_h_t *o, unsigned char in);


int decode_can_0x289_TempMotor(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x289_TempMotor(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x289_TempInv(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x289_TempInv(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x289_ErrInfo(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x289_ErrInfo(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x289_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x289_TempIGBT(can_obj_can1_h_t *o, uint16_t in);


int decode_can_0x28a_TempMotor(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x28a_TempMotor(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x28a_TempInv(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x28a_TempInv(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x28a_ErrorInfo(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x28a_ErrorInfo(can_obj_can1_h_t *o, uint16_t in);
int decode_can_0x28a_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out);
int encode_can_0x28a_TempIGBT(can_obj_can1_h_t *o, uint16_t in);


#ifdef __cplusplus
} 
#endif

#endif
