/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "can1.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x184_VCUInvFL(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x184_VCUInvFL.ControlWord)) & 0xffff;
	i |= x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x184_VCUInvFL.TargetVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x184_VCUInvFL.PosTorq)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* NegTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x184_VCUInvFL.NegTorq)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x184_VCUInvFL_tx = 1;
	return 8;
}

static int unpack_can_0x184_VCUInvFL(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x184_VCUInvFL.ControlWord = x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x184_VCUInvFL.TargetVel = x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x184_VCUInvFL.PosTorq = x;
	/* NegTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x184_VCUInvFL.NegTorq = x;
	o->can_0x184_VCUInvFL_rx = 1;
	o->can_0x184_VCUInvFL_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x184_ControlWord(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x184_VCUInvFL.ControlWord);
	*out = rval;
	return 0;
}

int encode_can_0x184_ControlWord(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x184_VCUInvFL.ControlWord = in;
	return 0;
}

int decode_can_0x184_TargetVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x184_VCUInvFL.TargetVel);
	*out = rval;
	return 0;
}

int encode_can_0x184_TargetVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x184_VCUInvFL.TargetVel = in;
	return 0;
}

int decode_can_0x184_PosTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x184_VCUInvFL.PosTorq);
	*out = rval;
	return 0;
}

int encode_can_0x184_PosTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x184_VCUInvFL.PosTorq = in;
	return 0;
}

int decode_can_0x184_NegTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x184_VCUInvFL.NegTorq);
	*out = rval;
	return 0;
}

int encode_can_0x184_NegTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x184_VCUInvFL.NegTorq = in;
	return 0;
}

int print_can_0x184_VCUInvFL(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ControlWord = (wire: %.0f)\n", (double)(o->can_0x184_VCUInvFL.ControlWord)));
	r = print_helper(r, fprintf(output, "TargetVel = (wire: %.0f)\n", (double)(o->can_0x184_VCUInvFL.TargetVel)));
	r = print_helper(r, fprintf(output, "PosTorq = (wire: %.0f)\n", (double)(o->can_0x184_VCUInvFL.PosTorq)));
	r = print_helper(r, fprintf(output, "NegTorq = (wire: %.0f)\n", (double)(o->can_0x184_VCUInvFL.NegTorq)));
	return r;
}

static int pack_can_0x185_VCUInvFR(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x185_VCUInvFR.ControlWord)) & 0xffff;
	i |= x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x185_VCUInvFR.TargetVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x185_VCUInvFR.PosTorq)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* negTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x185_VCUInvFR.negTorq)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x185_VCUInvFR_tx = 1;
	return 8;
}

static int unpack_can_0x185_VCUInvFR(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x185_VCUInvFR.ControlWord = x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x185_VCUInvFR.TargetVel = x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x185_VCUInvFR.PosTorq = x;
	/* negTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x185_VCUInvFR.negTorq = x;
	o->can_0x185_VCUInvFR_rx = 1;
	o->can_0x185_VCUInvFR_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x185_ControlWord(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x185_VCUInvFR.ControlWord);
	*out = rval;
	return 0;
}

int encode_can_0x185_ControlWord(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x185_VCUInvFR.ControlWord = in;
	return 0;
}

int decode_can_0x185_TargetVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x185_VCUInvFR.TargetVel);
	*out = rval;
	return 0;
}

int encode_can_0x185_TargetVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x185_VCUInvFR.TargetVel = in;
	return 0;
}

int decode_can_0x185_PosTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x185_VCUInvFR.PosTorq);
	*out = rval;
	return 0;
}

int encode_can_0x185_PosTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x185_VCUInvFR.PosTorq = in;
	return 0;
}

int decode_can_0x185_negTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x185_VCUInvFR.negTorq);
	*out = rval;
	return 0;
}

int encode_can_0x185_negTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x185_VCUInvFR.negTorq = in;
	return 0;
}

int print_can_0x185_VCUInvFR(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ControlWord = (wire: %.0f)\n", (double)(o->can_0x185_VCUInvFR.ControlWord)));
	r = print_helper(r, fprintf(output, "TargetVel = (wire: %.0f)\n", (double)(o->can_0x185_VCUInvFR.TargetVel)));
	r = print_helper(r, fprintf(output, "PosTorq = (wire: %.0f)\n", (double)(o->can_0x185_VCUInvFR.PosTorq)));
	r = print_helper(r, fprintf(output, "negTorq = (wire: %.0f)\n", (double)(o->can_0x185_VCUInvFR.negTorq)));
	return r;
}

static int pack_can_0x188_VCUInvRL(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x188_VCUInvRL.ControlWord)) & 0xffff;
	i |= x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x188_VCUInvRL.TargetVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x188_VCUInvRL.PosTorq)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* NegTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x188_VCUInvRL.NegTorq)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x188_VCUInvRL_tx = 1;
	return 8;
}

static int unpack_can_0x188_VCUInvRL(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x188_VCUInvRL.ControlWord = x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x188_VCUInvRL.TargetVel = x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x188_VCUInvRL.PosTorq = x;
	/* NegTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x188_VCUInvRL.NegTorq = x;
	o->can_0x188_VCUInvRL_rx = 1;
	o->can_0x188_VCUInvRL_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x188_ControlWord(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x188_VCUInvRL.ControlWord);
	*out = rval;
	return 0;
}

int encode_can_0x188_ControlWord(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x188_VCUInvRL.ControlWord = in;
	return 0;
}

int decode_can_0x188_TargetVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x188_VCUInvRL.TargetVel);
	*out = rval;
	return 0;
}

int encode_can_0x188_TargetVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x188_VCUInvRL.TargetVel = in;
	return 0;
}

int decode_can_0x188_PosTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x188_VCUInvRL.PosTorq);
	*out = rval;
	return 0;
}

int encode_can_0x188_PosTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x188_VCUInvRL.PosTorq = in;
	return 0;
}

int decode_can_0x188_NegTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x188_VCUInvRL.NegTorq);
	*out = rval;
	return 0;
}

int encode_can_0x188_NegTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x188_VCUInvRL.NegTorq = in;
	return 0;
}

int print_can_0x188_VCUInvRL(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ControlWord = (wire: %.0f)\n", (double)(o->can_0x188_VCUInvRL.ControlWord)));
	r = print_helper(r, fprintf(output, "TargetVel = (wire: %.0f)\n", (double)(o->can_0x188_VCUInvRL.TargetVel)));
	r = print_helper(r, fprintf(output, "PosTorq = (wire: %.0f)\n", (double)(o->can_0x188_VCUInvRL.PosTorq)));
	r = print_helper(r, fprintf(output, "NegTorq = (wire: %.0f)\n", (double)(o->can_0x188_VCUInvRL.NegTorq)));
	return r;
}

static int pack_can_0x189_VCUInvRR(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x189_VCUInvRR.ControlWord)) & 0xffff;
	i |= x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x189_VCUInvRR.TargetVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x189_VCUInvRR.PosTorq)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* NegTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x189_VCUInvRR.NegTorq)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x189_VCUInvRR_tx = 1;
	return 8;
}

static int unpack_can_0x189_VCUInvRR(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ControlWord: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x189_VCUInvRR.ControlWord = x;
	/* TargetVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x189_VCUInvRR.TargetVel = x;
	/* PosTorq: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x189_VCUInvRR.PosTorq = x;
	/* NegTorq: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x189_VCUInvRR.NegTorq = x;
	o->can_0x189_VCUInvRR_rx = 1;
	o->can_0x189_VCUInvRR_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x189_ControlWord(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x189_VCUInvRR.ControlWord);
	*out = rval;
	return 0;
}

int encode_can_0x189_ControlWord(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x189_VCUInvRR.ControlWord = in;
	return 0;
}

int decode_can_0x189_TargetVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x189_VCUInvRR.TargetVel);
	*out = rval;
	return 0;
}

int encode_can_0x189_TargetVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x189_VCUInvRR.TargetVel = in;
	return 0;
}

int decode_can_0x189_PosTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x189_VCUInvRR.PosTorq);
	*out = rval;
	return 0;
}

int encode_can_0x189_PosTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x189_VCUInvRR.PosTorq = in;
	return 0;
}

int decode_can_0x189_NegTorq(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x189_VCUInvRR.NegTorq);
	*out = rval;
	return 0;
}

int encode_can_0x189_NegTorq(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x189_VCUInvRR.NegTorq = in;
	return 0;
}

int print_can_0x189_VCUInvRR(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ControlWord = (wire: %.0f)\n", (double)(o->can_0x189_VCUInvRR.ControlWord)));
	r = print_helper(r, fprintf(output, "TargetVel = (wire: %.0f)\n", (double)(o->can_0x189_VCUInvRR.TargetVel)));
	r = print_helper(r, fprintf(output, "PosTorq = (wire: %.0f)\n", (double)(o->can_0x189_VCUInvRR.PosTorq)));
	r = print_helper(r, fprintf(output, "NegTorq = (wire: %.0f)\n", (double)(o->can_0x189_VCUInvRR.NegTorq)));
	return r;
}

static int pack_can_0x283_InverterFL1(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ActualVelocity: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x283_InverterFL1.ActualVelocity)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x283_InverterFL1.MagCurr)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x283_InverterFL1.TorqCurr)) & 0xffff;
	x <<= 48; 
	i |= x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x283_InverterFL1.Reserved)) & 0xff;
	i |= x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x283_InverterFL1.Status)) & 0xff;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x283_InverterFL1_tx = 1;
	return 8;
}

static int unpack_can_0x283_InverterFL1(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ActualVelocity: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x283_InverterFL1.ActualVelocity = x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x283_InverterFL1.MagCurr = x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x283_InverterFL1.TorqCurr = x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x283_InverterFL1.Reserved = x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x283_InverterFL1.Status = x;
	o->can_0x283_InverterFL1_rx = 1;
	o->can_0x283_InverterFL1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x283_ActualVelocity(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x283_InverterFL1.ActualVelocity);
	*out = rval;
	return 0;
}

int encode_can_0x283_ActualVelocity(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x283_InverterFL1.ActualVelocity = in;
	return 0;
}

int decode_can_0x283_MagCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x283_InverterFL1.MagCurr);
	*out = rval;
	return 0;
}

int encode_can_0x283_MagCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x283_InverterFL1.MagCurr = in;
	return 0;
}

int decode_can_0x283_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x283_InverterFL1.TorqCurr);
	*out = rval;
	return 0;
}

int encode_can_0x283_TorqCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x283_InverterFL1.TorqCurr = in;
	return 0;
}

int decode_can_0x283_Reserved(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x283_InverterFL1.Reserved);
	*out = rval;
	return 0;
}

int encode_can_0x283_Reserved(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x283_InverterFL1.Reserved = in;
	return 0;
}

int decode_can_0x283_Status(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x283_InverterFL1.Status);
	*out = rval;
	return 0;
}

int encode_can_0x283_Status(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x283_InverterFL1.Status = in;
	return 0;
}

int print_can_0x283_InverterFL1(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ActualVelocity = (wire: %.0f)\n", (double)(o->can_0x283_InverterFL1.ActualVelocity)));
	r = print_helper(r, fprintf(output, "MagCurr = (wire: %.0f)\n", (double)(o->can_0x283_InverterFL1.MagCurr)));
	r = print_helper(r, fprintf(output, "TorqCurr = (wire: %.0f)\n", (double)(o->can_0x283_InverterFL1.TorqCurr)));
	r = print_helper(r, fprintf(output, "Reserved = (wire: %.0f)\n", (double)(o->can_0x283_InverterFL1.Reserved)));
	r = print_helper(r, fprintf(output, "Status = (wire: %.0f)\n", (double)(o->can_0x283_InverterFL1.Status)));
	return r;
}

static int pack_can_0x284_InverterFR1(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ActualVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x284_InverterFR1.ActualVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x284_InverterFR1.MagCurr)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x284_InverterFR1.TorqCurr)) & 0xffff;
	x <<= 48; 
	i |= x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x284_InverterFR1.Reserved)) & 0xff;
	i |= x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x284_InverterFR1.Status)) & 0xff;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x284_InverterFR1_tx = 1;
	return 8;
}

static int unpack_can_0x284_InverterFR1(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ActualVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x284_InverterFR1.ActualVel = x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x284_InverterFR1.MagCurr = x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x284_InverterFR1.TorqCurr = x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x284_InverterFR1.Reserved = x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x284_InverterFR1.Status = x;
	o->can_0x284_InverterFR1_rx = 1;
	o->can_0x284_InverterFR1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x284_ActualVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x284_InverterFR1.ActualVel);
	*out = rval;
	return 0;
}

int encode_can_0x284_ActualVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x284_InverterFR1.ActualVel = in;
	return 0;
}

int decode_can_0x284_MagCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x284_InverterFR1.MagCurr);
	*out = rval;
	return 0;
}

int encode_can_0x284_MagCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x284_InverterFR1.MagCurr = in;
	return 0;
}

int decode_can_0x284_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x284_InverterFR1.TorqCurr);
	*out = rval;
	return 0;
}

int encode_can_0x284_TorqCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x284_InverterFR1.TorqCurr = in;
	return 0;
}

int decode_can_0x284_Reserved(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x284_InverterFR1.Reserved);
	*out = rval;
	return 0;
}

int encode_can_0x284_Reserved(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x284_InverterFR1.Reserved = in;
	return 0;
}

int decode_can_0x284_Status(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x284_InverterFR1.Status);
	*out = rval;
	return 0;
}

int encode_can_0x284_Status(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x284_InverterFR1.Status = in;
	return 0;
}

int print_can_0x284_InverterFR1(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ActualVel = (wire: %.0f)\n", (double)(o->can_0x284_InverterFR1.ActualVel)));
	r = print_helper(r, fprintf(output, "MagCurr = (wire: %.0f)\n", (double)(o->can_0x284_InverterFR1.MagCurr)));
	r = print_helper(r, fprintf(output, "TorqCurr = (wire: %.0f)\n", (double)(o->can_0x284_InverterFR1.TorqCurr)));
	r = print_helper(r, fprintf(output, "Reserved = (wire: %.0f)\n", (double)(o->can_0x284_InverterFR1.Reserved)));
	r = print_helper(r, fprintf(output, "Status = (wire: %.0f)\n", (double)(o->can_0x284_InverterFR1.Status)));
	return r;
}

static int pack_can_0x285_InverterFL2(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x285_InverterFL2.TempMotor)) & 0xffff;
	i |= x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x285_InverterFL2.TempInv)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* Error: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x285_InverterFL2.Error)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x285_InverterFL2.TempIGBT)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x285_InverterFL2_tx = 1;
	return 8;
}

static int unpack_can_0x285_InverterFL2(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x285_InverterFL2.TempMotor = x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x285_InverterFL2.TempInv = x;
	/* Error: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x285_InverterFL2.Error = x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x285_InverterFL2.TempIGBT = x;
	o->can_0x285_InverterFL2_rx = 1;
	o->can_0x285_InverterFL2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x285_TempMotor(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x285_InverterFL2.TempMotor);
	*out = rval;
	return 0;
}

int encode_can_0x285_TempMotor(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x285_InverterFL2.TempMotor = in;
	return 0;
}

int decode_can_0x285_TempInv(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x285_InverterFL2.TempInv);
	*out = rval;
	return 0;
}

int encode_can_0x285_TempInv(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x285_InverterFL2.TempInv = in;
	return 0;
}

int decode_can_0x285_Error(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x285_InverterFL2.Error);
	*out = rval;
	return 0;
}

int encode_can_0x285_Error(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x285_InverterFL2.Error = in;
	return 0;
}

int decode_can_0x285_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x285_InverterFL2.TempIGBT);
	*out = rval;
	return 0;
}

int encode_can_0x285_TempIGBT(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x285_InverterFL2.TempIGBT = in;
	return 0;
}

int print_can_0x285_InverterFL2(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TempMotor = (wire: %.0f)\n", (double)(o->can_0x285_InverterFL2.TempMotor)));
	r = print_helper(r, fprintf(output, "TempInv = (wire: %.0f)\n", (double)(o->can_0x285_InverterFL2.TempInv)));
	r = print_helper(r, fprintf(output, "Error = (wire: %.0f)\n", (double)(o->can_0x285_InverterFL2.Error)));
	r = print_helper(r, fprintf(output, "TempIGBT = (wire: %.0f)\n", (double)(o->can_0x285_InverterFL2.TempIGBT)));
	return r;
}

static int pack_can_0x286_InverterFR2(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x286_InverterFR2.TempMotor)) & 0xffff;
	i |= x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x286_InverterFR2.TempInv)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* ErrorInfo: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x286_InverterFR2.ErrorInfo)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x286_InverterFR2.TempIGBT)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x286_InverterFR2_tx = 1;
	return 8;
}

static int unpack_can_0x286_InverterFR2(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x286_InverterFR2.TempMotor = x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x286_InverterFR2.TempInv = x;
	/* ErrorInfo: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x286_InverterFR2.ErrorInfo = x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x286_InverterFR2.TempIGBT = x;
	o->can_0x286_InverterFR2_rx = 1;
	o->can_0x286_InverterFR2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x286_TempMotor(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x286_InverterFR2.TempMotor);
	*out = rval;
	return 0;
}

int encode_can_0x286_TempMotor(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x286_InverterFR2.TempMotor = in;
	return 0;
}

int decode_can_0x286_TempInv(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x286_InverterFR2.TempInv);
	*out = rval;
	return 0;
}

int encode_can_0x286_TempInv(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x286_InverterFR2.TempInv = in;
	return 0;
}

int decode_can_0x286_ErrorInfo(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x286_InverterFR2.ErrorInfo);
	*out = rval;
	return 0;
}

int encode_can_0x286_ErrorInfo(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x286_InverterFR2.ErrorInfo = in;
	return 0;
}

int decode_can_0x286_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x286_InverterFR2.TempIGBT);
	*out = rval;
	return 0;
}

int encode_can_0x286_TempIGBT(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x286_InverterFR2.TempIGBT = in;
	return 0;
}

int print_can_0x286_InverterFR2(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TempMotor = (wire: %.0f)\n", (double)(o->can_0x286_InverterFR2.TempMotor)));
	r = print_helper(r, fprintf(output, "TempInv = (wire: %.0f)\n", (double)(o->can_0x286_InverterFR2.TempInv)));
	r = print_helper(r, fprintf(output, "ErrorInfo = (wire: %.0f)\n", (double)(o->can_0x286_InverterFR2.ErrorInfo)));
	r = print_helper(r, fprintf(output, "TempIGBT = (wire: %.0f)\n", (double)(o->can_0x286_InverterFR2.TempIGBT)));
	return r;
}

static int pack_can_0x287_InverterRL1(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ActualVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x287_InverterRL1.ActualVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x287_InverterRL1.MagCurr)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x287_InverterRL1.TorqCurr)) & 0xffff;
	x <<= 48; 
	i |= x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x287_InverterRL1.Reserved)) & 0xff;
	i |= x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x287_InverterRL1.Status)) & 0xff;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x287_InverterRL1_tx = 1;
	return 8;
}

static int unpack_can_0x287_InverterRL1(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ActualVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x287_InverterRL1.ActualVel = x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x287_InverterRL1.MagCurr = x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x287_InverterRL1.TorqCurr = x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x287_InverterRL1.Reserved = x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x287_InverterRL1.Status = x;
	o->can_0x287_InverterRL1_rx = 1;
	o->can_0x287_InverterRL1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x287_ActualVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x287_InverterRL1.ActualVel);
	*out = rval;
	return 0;
}

int encode_can_0x287_ActualVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x287_InverterRL1.ActualVel = in;
	return 0;
}

int decode_can_0x287_MagCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x287_InverterRL1.MagCurr);
	*out = rval;
	return 0;
}

int encode_can_0x287_MagCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x287_InverterRL1.MagCurr = in;
	return 0;
}

int decode_can_0x287_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x287_InverterRL1.TorqCurr);
	*out = rval;
	return 0;
}

int encode_can_0x287_TorqCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x287_InverterRL1.TorqCurr = in;
	return 0;
}

int decode_can_0x287_Reserved(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x287_InverterRL1.Reserved);
	*out = rval;
	return 0;
}

int encode_can_0x287_Reserved(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x287_InverterRL1.Reserved = in;
	return 0;
}

int decode_can_0x287_Status(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x287_InverterRL1.Status);
	*out = rval;
	return 0;
}

int encode_can_0x287_Status(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x287_InverterRL1.Status = in;
	return 0;
}

int print_can_0x287_InverterRL1(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ActualVel = (wire: %.0f)\n", (double)(o->can_0x287_InverterRL1.ActualVel)));
	r = print_helper(r, fprintf(output, "MagCurr = (wire: %.0f)\n", (double)(o->can_0x287_InverterRL1.MagCurr)));
	r = print_helper(r, fprintf(output, "TorqCurr = (wire: %.0f)\n", (double)(o->can_0x287_InverterRL1.TorqCurr)));
	r = print_helper(r, fprintf(output, "Reserved = (wire: %.0f)\n", (double)(o->can_0x287_InverterRL1.Reserved)));
	r = print_helper(r, fprintf(output, "Status = (wire: %.0f)\n", (double)(o->can_0x287_InverterRL1.Status)));
	return r;
}

static int pack_can_0x288_InverterRR1(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ActualVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x288_InverterRR1.ActualVel)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x288_InverterRR1.MagCurr)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x288_InverterRR1.TorqCurr)) & 0xffff;
	x <<= 48; 
	i |= x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x288_InverterRR1.Reserved)) & 0xff;
	i |= x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x288_InverterRR1.Status)) & 0xff;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x288_InverterRR1_tx = 1;
	return 8;
}

static int unpack_can_0x288_InverterRR1(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ActualVel: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x288_InverterRR1.ActualVel = x;
	/* MagCurr: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x288_InverterRR1.MagCurr = x;
	/* TorqCurr: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x288_InverterRR1.TorqCurr = x;
	/* Reserved: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x288_InverterRR1.Reserved = x;
	/* Status: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x288_InverterRR1.Status = x;
	o->can_0x288_InverterRR1_rx = 1;
	o->can_0x288_InverterRR1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x288_ActualVel(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x288_InverterRR1.ActualVel);
	*out = rval;
	return 0;
}

int encode_can_0x288_ActualVel(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x288_InverterRR1.ActualVel = in;
	return 0;
}

int decode_can_0x288_MagCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x288_InverterRR1.MagCurr);
	*out = rval;
	return 0;
}

int encode_can_0x288_MagCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x288_InverterRR1.MagCurr = in;
	return 0;
}

int decode_can_0x288_TorqCurr(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x288_InverterRR1.TorqCurr);
	*out = rval;
	return 0;
}

int encode_can_0x288_TorqCurr(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x288_InverterRR1.TorqCurr = in;
	return 0;
}

int decode_can_0x288_Reserved(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x288_InverterRR1.Reserved);
	*out = rval;
	return 0;
}

int encode_can_0x288_Reserved(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x288_InverterRR1.Reserved = in;
	return 0;
}

int decode_can_0x288_Status(const can_obj_can1_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x288_InverterRR1.Status);
	*out = rval;
	return 0;
}

int encode_can_0x288_Status(can_obj_can1_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x288_InverterRR1.Status = in;
	return 0;
}

int print_can_0x288_InverterRR1(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ActualVel = (wire: %.0f)\n", (double)(o->can_0x288_InverterRR1.ActualVel)));
	r = print_helper(r, fprintf(output, "MagCurr = (wire: %.0f)\n", (double)(o->can_0x288_InverterRR1.MagCurr)));
	r = print_helper(r, fprintf(output, "TorqCurr = (wire: %.0f)\n", (double)(o->can_0x288_InverterRR1.TorqCurr)));
	r = print_helper(r, fprintf(output, "Reserved = (wire: %.0f)\n", (double)(o->can_0x288_InverterRR1.Reserved)));
	r = print_helper(r, fprintf(output, "Status = (wire: %.0f)\n", (double)(o->can_0x288_InverterRR1.Status)));
	return r;
}

static int pack_can_0x289_InverterRL2(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x289_InverterRL2.TempMotor)) & 0xffff;
	i |= x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x289_InverterRL2.TempInv)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* ErrInfo: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x289_InverterRL2.ErrInfo)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x289_InverterRL2.TempIGBT)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x289_InverterRL2_tx = 1;
	return 8;
}

static int unpack_can_0x289_InverterRL2(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x289_InverterRL2.TempMotor = x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x289_InverterRL2.TempInv = x;
	/* ErrInfo: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x289_InverterRL2.ErrInfo = x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x289_InverterRL2.TempIGBT = x;
	o->can_0x289_InverterRL2_rx = 1;
	o->can_0x289_InverterRL2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x289_TempMotor(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x289_InverterRL2.TempMotor);
	*out = rval;
	return 0;
}

int encode_can_0x289_TempMotor(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x289_InverterRL2.TempMotor = in;
	return 0;
}

int decode_can_0x289_TempInv(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x289_InverterRL2.TempInv);
	*out = rval;
	return 0;
}

int encode_can_0x289_TempInv(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x289_InverterRL2.TempInv = in;
	return 0;
}

int decode_can_0x289_ErrInfo(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x289_InverterRL2.ErrInfo);
	*out = rval;
	return 0;
}

int encode_can_0x289_ErrInfo(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x289_InverterRL2.ErrInfo = in;
	return 0;
}

int decode_can_0x289_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x289_InverterRL2.TempIGBT);
	*out = rval;
	return 0;
}

int encode_can_0x289_TempIGBT(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x289_InverterRL2.TempIGBT = in;
	return 0;
}

int print_can_0x289_InverterRL2(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TempMotor = (wire: %.0f)\n", (double)(o->can_0x289_InverterRL2.TempMotor)));
	r = print_helper(r, fprintf(output, "TempInv = (wire: %.0f)\n", (double)(o->can_0x289_InverterRL2.TempInv)));
	r = print_helper(r, fprintf(output, "ErrInfo = (wire: %.0f)\n", (double)(o->can_0x289_InverterRL2.ErrInfo)));
	r = print_helper(r, fprintf(output, "TempIGBT = (wire: %.0f)\n", (double)(o->can_0x289_InverterRL2.TempIGBT)));
	return r;
}

static int pack_can_0x28a_InverterRR2(can_obj_can1_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x28a_InverterRR2.TempMotor)) & 0xffff;
	i |= x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x28a_InverterRR2.TempInv)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* ErrorInfo: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x28a_InverterRR2.ErrorInfo)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x28a_InverterRR2.TempIGBT)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x28a_InverterRR2_tx = 1;
	return 8;
}

static int unpack_can_0x28a_InverterRR2(can_obj_can1_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TempMotor: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x28a_InverterRR2.TempMotor = x;
	/* TempInv: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x28a_InverterRR2.TempInv = x;
	/* ErrorInfo: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x28a_InverterRR2.ErrorInfo = x;
	/* TempIGBT: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x28a_InverterRR2.TempIGBT = x;
	o->can_0x28a_InverterRR2_rx = 1;
	o->can_0x28a_InverterRR2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x28a_TempMotor(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x28a_InverterRR2.TempMotor);
	*out = rval;
	return 0;
}

int encode_can_0x28a_TempMotor(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x28a_InverterRR2.TempMotor = in;
	return 0;
}

int decode_can_0x28a_TempInv(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x28a_InverterRR2.TempInv);
	*out = rval;
	return 0;
}

int encode_can_0x28a_TempInv(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x28a_InverterRR2.TempInv = in;
	return 0;
}

int decode_can_0x28a_ErrorInfo(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x28a_InverterRR2.ErrorInfo);
	*out = rval;
	return 0;
}

int encode_can_0x28a_ErrorInfo(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x28a_InverterRR2.ErrorInfo = in;
	return 0;
}

int decode_can_0x28a_TempIGBT(const can_obj_can1_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x28a_InverterRR2.TempIGBT);
	*out = rval;
	return 0;
}

int encode_can_0x28a_TempIGBT(can_obj_can1_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x28a_InverterRR2.TempIGBT = in;
	return 0;
}

int print_can_0x28a_InverterRR2(const can_obj_can1_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TempMotor = (wire: %.0f)\n", (double)(o->can_0x28a_InverterRR2.TempMotor)));
	r = print_helper(r, fprintf(output, "TempInv = (wire: %.0f)\n", (double)(o->can_0x28a_InverterRR2.TempInv)));
	r = print_helper(r, fprintf(output, "ErrorInfo = (wire: %.0f)\n", (double)(o->can_0x28a_InverterRR2.ErrorInfo)));
	r = print_helper(r, fprintf(output, "TempIGBT = (wire: %.0f)\n", (double)(o->can_0x28a_InverterRR2.TempIGBT)));
	return r;
}

int unpack_message(can_obj_can1_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x184: return unpack_can_0x184_VCUInvFL(o, data, dlc, time_stamp);
	case 0x185: return unpack_can_0x185_VCUInvFR(o, data, dlc, time_stamp);
	case 0x188: return unpack_can_0x188_VCUInvRL(o, data, dlc, time_stamp);
	case 0x189: return unpack_can_0x189_VCUInvRR(o, data, dlc, time_stamp);
	case 0x283: return unpack_can_0x283_InverterFL1(o, data, dlc, time_stamp);
	case 0x284: return unpack_can_0x284_InverterFR1(o, data, dlc, time_stamp);
	case 0x285: return unpack_can_0x285_InverterFL2(o, data, dlc, time_stamp);
	case 0x286: return unpack_can_0x286_InverterFR2(o, data, dlc, time_stamp);
	case 0x287: return unpack_can_0x287_InverterRL1(o, data, dlc, time_stamp);
	case 0x288: return unpack_can_0x288_InverterRR1(o, data, dlc, time_stamp);
	case 0x289: return unpack_can_0x289_InverterRL2(o, data, dlc, time_stamp);
	case 0x28a: return unpack_can_0x28a_InverterRR2(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_can1_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x184: return pack_can_0x184_VCUInvFL(o, data);
	case 0x185: return pack_can_0x185_VCUInvFR(o, data);
	case 0x188: return pack_can_0x188_VCUInvRL(o, data);
	case 0x189: return pack_can_0x189_VCUInvRR(o, data);
	case 0x283: return pack_can_0x283_InverterFL1(o, data);
	case 0x284: return pack_can_0x284_InverterFR1(o, data);
	case 0x285: return pack_can_0x285_InverterFL2(o, data);
	case 0x286: return pack_can_0x286_InverterFR2(o, data);
	case 0x287: return pack_can_0x287_InverterRL1(o, data);
	case 0x288: return pack_can_0x288_InverterRR1(o, data);
	case 0x289: return pack_can_0x289_InverterRL2(o, data);
	case 0x28a: return pack_can_0x28a_InverterRR2(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_can1_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x184: return print_can_0x184_VCUInvFL(o, output);
	case 0x185: return print_can_0x185_VCUInvFR(o, output);
	case 0x188: return print_can_0x188_VCUInvRL(o, output);
	case 0x189: return print_can_0x189_VCUInvRR(o, output);
	case 0x283: return print_can_0x283_InverterFL1(o, output);
	case 0x284: return print_can_0x284_InverterFR1(o, output);
	case 0x285: return print_can_0x285_InverterFL2(o, output);
	case 0x286: return print_can_0x286_InverterFR2(o, output);
	case 0x287: return print_can_0x287_InverterRL1(o, output);
	case 0x288: return print_can_0x288_InverterRR1(o, output);
	case 0x289: return print_can_0x289_InverterRL2(o, output);
	case 0x28a: return print_can_0x28a_InverterRR2(o, output);
	default: break; 
	}
	return -1; 
}

