/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "can2.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x053_Driver(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* steering: start-bit 16, length 12, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x053_Driver.steering)) & 0xfff;
	x <<= 16; 
	i |= x;
	/* throttle: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.throttle)) & 0xff;
	i |= x;
	/* brake: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.brake)) & 0xff;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x053_Driver_tx = 1;
	return 4;
}

static int unpack_can_0x053_Driver(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 4)
		return -1;
	/* steering: start-bit 16, length 12, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xfff;
	x = (x & 0x800) ? (x | 0xf000) : x; 
	o->can_0x053_Driver.steering = x;
	/* throttle: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x053_Driver.throttle = x;
	/* brake: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x053_Driver.brake = x;
	o->can_0x053_Driver_rx = 1;
	o->can_0x053_Driver_time_stamp_rx = time_stamp;
	return 4;
}

int decode_can_0x053_steering(const can_obj_can2_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0x053_Driver.steering);
	if ((rval >= -1570) && (rval <= 1570)) {
		*out = rval;
		return 0;
	} else {
		*out = (int16_t)0;
		return -1;
	}
}

int encode_can_0x053_steering(can_obj_can2_h_t *o, int16_t in) {
	assert(o);
	o->can_0x053_Driver.steering = 0;
	if (in < -1570)
		return -1;
	if (in > 1570)
		return -1;
	o->can_0x053_Driver.steering = in;
	return 0;
}

int decode_can_0x053_throttle(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.throttle);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x053_throttle(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.throttle = 0;
	if (in > 100)
		return -1;
	o->can_0x053_Driver.throttle = in;
	return 0;
}

int decode_can_0x053_brake(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.brake);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x053_brake(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.brake = 0;
	if (in > 100)
		return -1;
	o->can_0x053_Driver.brake = in;
	return 0;
}

int print_can_0x053_Driver(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "steering = (wire: %.0f)\n", (double)(o->can_0x053_Driver.steering)));
	r = print_helper(r, fprintf(output, "throttle = (wire: %.0f)\n", (double)(o->can_0x053_Driver.throttle)));
	r = print_helper(r, fprintf(output, "brake = (wire: %.0f)\n", (double)(o->can_0x053_Driver.brake)));
	return r;
}

static int pack_can_0x054_Paddle(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* regen: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x054_Paddle.regen)) & 0xff;
	i |= x;
	*data = (i);
	o->can_0x054_Paddle_tx = 1;
	return 1;
}

static int unpack_can_0x054_Paddle(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* regen: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x054_Paddle.regen = x;
	o->can_0x054_Paddle_rx = 1;
	o->can_0x054_Paddle_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x054_regen(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x054_Paddle.regen);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x054_regen(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x054_Paddle.regen = 0;
	if (in > 100)
		return -1;
	o->can_0x054_Paddle.regen = in;
	return 0;
}

int print_can_0x054_Paddle(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "regen = (wire: %.0f)\n", (double)(o->can_0x054_Paddle.regen)));
	return r;
}

static int pack_can_0x055_BmsHv1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* max_volt: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x055_BmsHv1.max_volt)) & 0xffff;
	i |= x;
	/* min_volt: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x055_BmsHv1.min_volt)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* avg_volt: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x055_BmsHv1.avg_volt)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* soc: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x055_BmsHv1.soc)) & 0xff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x055_BmsHv1_tx = 1;
	return 7;
}

static int unpack_can_0x055_BmsHv1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 7)
		return -1;
	/* max_volt: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x055_BmsHv1.max_volt = x;
	/* min_volt: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x055_BmsHv1.min_volt = x;
	/* avg_volt: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x055_BmsHv1.avg_volt = x;
	/* soc: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x055_BmsHv1.soc = x;
	o->can_0x055_BmsHv1_rx = 1;
	o->can_0x055_BmsHv1_time_stamp_rx = time_stamp;
	return 7;
}

int decode_can_0x055_max_volt(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsHv1.max_volt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x055_max_volt(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x055_BmsHv1.max_volt = in;
	return 0;
}

int decode_can_0x055_min_volt(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsHv1.min_volt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x055_min_volt(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x055_BmsHv1.min_volt = in;
	return 0;
}

int decode_can_0x055_avg_volt(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsHv1.avg_volt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x055_avg_volt(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x055_BmsHv1.avg_volt = in;
	return 0;
}

int decode_can_0x055_soc(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x055_BmsHv1.soc);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x055_soc(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x055_BmsHv1.soc = 0;
	if (in > 100)
		return -1;
	o->can_0x055_BmsHv1.soc = in;
	return 0;
}

int print_can_0x055_BmsHv1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_volt = (wire: %.0f)\n", (double)(o->can_0x055_BmsHv1.max_volt)));
	r = print_helper(r, fprintf(output, "min_volt = (wire: %.0f)\n", (double)(o->can_0x055_BmsHv1.min_volt)));
	r = print_helper(r, fprintf(output, "avg_volt = (wire: %.0f)\n", (double)(o->can_0x055_BmsHv1.avg_volt)));
	r = print_helper(r, fprintf(output, "soc = (wire: %.0f)\n", (double)(o->can_0x055_BmsHv1.soc)));
	return r;
}

static int pack_can_0x056_BmsHv2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* max_temp: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x056_BmsHv2.max_temp)) & 0xffff;
	i |= x;
	/* min_temp: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x056_BmsHv2.min_temp)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* avg_temp: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x056_BmsHv2.avg_temp)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* fan_speed: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x056_BmsHv2.fan_speed)) & 0xff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x056_BmsHv2_tx = 1;
	return 7;
}

static int unpack_can_0x056_BmsHv2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 7)
		return -1;
	/* max_temp: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x056_BmsHv2.max_temp = x;
	/* min_temp: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x056_BmsHv2.min_temp = x;
	/* avg_temp: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x056_BmsHv2.avg_temp = x;
	/* fan_speed: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x056_BmsHv2.fan_speed = x;
	o->can_0x056_BmsHv2_rx = 1;
	o->can_0x056_BmsHv2_time_stamp_rx = time_stamp;
	return 7;
}

int decode_can_0x056_max_temp(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x056_BmsHv2.max_temp);
	*out = rval;
	return 0;
}

int encode_can_0x056_max_temp(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x056_BmsHv2.max_temp = in;
	return 0;
}

int decode_can_0x056_min_temp(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x056_BmsHv2.min_temp);
	*out = rval;
	return 0;
}

int encode_can_0x056_min_temp(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x056_BmsHv2.min_temp = in;
	return 0;
}

int decode_can_0x056_avg_temp(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x056_BmsHv2.avg_temp);
	*out = rval;
	return 0;
}

int encode_can_0x056_avg_temp(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x056_BmsHv2.avg_temp = in;
	return 0;
}

int decode_can_0x056_fan_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x056_BmsHv2.fan_speed);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x056_fan_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x056_BmsHv2.fan_speed = 0;
	if (in > 100)
		return -1;
	o->can_0x056_BmsHv2.fan_speed = in;
	return 0;
}

int print_can_0x056_BmsHv2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_temp = (wire: %.0f)\n", (double)(o->can_0x056_BmsHv2.max_temp)));
	r = print_helper(r, fprintf(output, "min_temp = (wire: %.0f)\n", (double)(o->can_0x056_BmsHv2.min_temp)));
	r = print_helper(r, fprintf(output, "avg_temp = (wire: %.0f)\n", (double)(o->can_0x056_BmsHv2.avg_temp)));
	r = print_helper(r, fprintf(output, "fan_speed = (wire: %.0f)\n", (double)(o->can_0x056_BmsHv2.fan_speed)));
	return r;
}

static int pack_can_0x057_BmsLv1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* volt1: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsLv1.volt1)) & 0xffff;
	i |= x;
	/* volt2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsLv1.volt2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* volt3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsLv1.volt3)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* volt4: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsLv1.volt4)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x057_BmsLv1_tx = 1;
	return 8;
}

static int unpack_can_0x057_BmsLv1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* volt1: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x057_BmsLv1.volt1 = x;
	/* volt2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x057_BmsLv1.volt2 = x;
	/* volt3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x057_BmsLv1.volt3 = x;
	/* volt4: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x057_BmsLv1.volt4 = x;
	o->can_0x057_BmsLv1_rx = 1;
	o->can_0x057_BmsLv1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x057_volt1(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsLv1.volt1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_volt1(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsLv1.volt1 = in;
	return 0;
}

int decode_can_0x057_volt2(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsLv1.volt2);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_volt2(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsLv1.volt2 = in;
	return 0;
}

int decode_can_0x057_volt3(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsLv1.volt3);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_volt3(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsLv1.volt3 = in;
	return 0;
}

int decode_can_0x057_volt4(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsLv1.volt4);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_volt4(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsLv1.volt4 = in;
	return 0;
}

int print_can_0x057_BmsLv1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "volt1 = (wire: %.0f)\n", (double)(o->can_0x057_BmsLv1.volt1)));
	r = print_helper(r, fprintf(output, "volt2 = (wire: %.0f)\n", (double)(o->can_0x057_BmsLv1.volt2)));
	r = print_helper(r, fprintf(output, "volt3 = (wire: %.0f)\n", (double)(o->can_0x057_BmsLv1.volt3)));
	r = print_helper(r, fprintf(output, "volt4 = (wire: %.0f)\n", (double)(o->can_0x057_BmsLv1.volt4)));
	return r;
}

static int pack_can_0x058_BmsLv2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* volt5: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsLv2.volt5)) & 0xffff;
	i |= x;
	/* volt6: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsLv2.volt6)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* temp1: start-bit 32, length 16, endianess intel, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsLv2.temp1)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* temp2: start-bit 48, length 16, endianess intel, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsLv2.temp2)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x058_BmsLv2_tx = 1;
	return 8;
}

static int unpack_can_0x058_BmsLv2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* volt5: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x058_BmsLv2.volt5 = x;
	/* volt6: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x058_BmsLv2.volt6 = x;
	/* temp1: start-bit 32, length 16, endianess intel, scaling 0.001, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x058_BmsLv2.temp1 = x;
	/* temp2: start-bit 48, length 16, endianess intel, scaling 0.001, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x058_BmsLv2.temp2 = x;
	o->can_0x058_BmsLv2_rx = 1;
	o->can_0x058_BmsLv2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x058_volt5(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x058_BmsLv2.volt5);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x058_volt5(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x058_BmsLv2.volt5 = in;
	return 0;
}

int decode_can_0x058_volt6(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x058_BmsLv2.volt6);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x058_volt6(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x058_BmsLv2.volt6 = in;
	return 0;
}

int decode_can_0x058_temp1(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x058_BmsLv2.temp1);
	rval *= 0.001;
	*out = rval;
	return 0;
}

int encode_can_0x058_temp1(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 1000;
	o->can_0x058_BmsLv2.temp1 = in;
	return 0;
}

int decode_can_0x058_temp2(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x058_BmsLv2.temp2);
	rval *= 0.001;
	*out = rval;
	return 0;
}

int encode_can_0x058_temp2(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 1000;
	o->can_0x058_BmsLv2.temp2 = in;
	return 0;
}

int print_can_0x058_BmsLv2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "volt5 = (wire: %.0f)\n", (double)(o->can_0x058_BmsLv2.volt5)));
	r = print_helper(r, fprintf(output, "volt6 = (wire: %.0f)\n", (double)(o->can_0x058_BmsLv2.volt6)));
	r = print_helper(r, fprintf(output, "temp1 = (wire: %.0f)\n", (double)(o->can_0x058_BmsLv2.temp1)));
	r = print_helper(r, fprintf(output, "temp2 = (wire: %.0f)\n", (double)(o->can_0x058_BmsLv2.temp2)));
	return r;
}

static int pack_can_0x060_Imu1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* acc_x: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x060_Imu1.acc_x)) & 0xffffffff;
	i |= x;
	/* acc_y: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x060_Imu1.acc_y)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x060_Imu1_tx = 1;
	return 8;
}

static int unpack_can_0x060_Imu1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* acc_x: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x060_Imu1.acc_x = x;
	/* acc_y: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x060_Imu1.acc_y = x;
	o->can_0x060_Imu1_rx = 1;
	o->can_0x060_Imu1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x060_acc_x(const can_obj_can2_h_t *o, int32_t *out) {
	assert(o);
	assert(out);
	int32_t rval = (int32_t)(o->can_0x060_Imu1.acc_x);
	*out = rval;
	return 0;
}

int encode_can_0x060_acc_x(can_obj_can2_h_t *o, int32_t in) {
	assert(o);
	o->can_0x060_Imu1.acc_x = in;
	return 0;
}

int decode_can_0x060_acc_y(const can_obj_can2_h_t *o, int32_t *out) {
	assert(o);
	assert(out);
	int32_t rval = (int32_t)(o->can_0x060_Imu1.acc_y);
	*out = rval;
	return 0;
}

int encode_can_0x060_acc_y(can_obj_can2_h_t *o, int32_t in) {
	assert(o);
	o->can_0x060_Imu1.acc_y = in;
	return 0;
}

int print_can_0x060_Imu1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "acc_x = (wire: %.0f)\n", (double)(o->can_0x060_Imu1.acc_x)));
	r = print_helper(r, fprintf(output, "acc_y = (wire: %.0f)\n", (double)(o->can_0x060_Imu1.acc_y)));
	return r;
}

static int pack_can_0x061_Imu2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* acc_z: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x061_Imu2.acc_z)) & 0xffffffff;
	i |= x;
	/* omega_x: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x061_Imu2.omega_x)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x061_Imu2_tx = 1;
	return 8;
}

static int unpack_can_0x061_Imu2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* acc_z: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x061_Imu2.acc_z = x;
	/* omega_x: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x061_Imu2.omega_x = x;
	o->can_0x061_Imu2_rx = 1;
	o->can_0x061_Imu2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x061_acc_z(const can_obj_can2_h_t *o, int32_t *out) {
	assert(o);
	assert(out);
	int32_t rval = (int32_t)(o->can_0x061_Imu2.acc_z);
	*out = rval;
	return 0;
}

int encode_can_0x061_acc_z(can_obj_can2_h_t *o, int32_t in) {
	assert(o);
	o->can_0x061_Imu2.acc_z = in;
	return 0;
}

int decode_can_0x061_omega_x(const can_obj_can2_h_t *o, int32_t *out) {
	assert(o);
	assert(out);
	int32_t rval = (int32_t)(o->can_0x061_Imu2.omega_x);
	*out = rval;
	return 0;
}

int encode_can_0x061_omega_x(can_obj_can2_h_t *o, int32_t in) {
	assert(o);
	o->can_0x061_Imu2.omega_x = in;
	return 0;
}

int print_can_0x061_Imu2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "acc_z = (wire: %.0f)\n", (double)(o->can_0x061_Imu2.acc_z)));
	r = print_helper(r, fprintf(output, "omega_x = (wire: %.0f)\n", (double)(o->can_0x061_Imu2.omega_x)));
	return r;
}

static int pack_can_0x062_Imu3(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* omega_y: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x062_Imu3.omega_y)) & 0xffffffff;
	i |= x;
	/* omega_z: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x062_Imu3.omega_z)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x062_Imu3_tx = 1;
	return 8;
}

static int unpack_can_0x062_Imu3(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* omega_y: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x062_Imu3.omega_y = x;
	/* omega_z: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x062_Imu3.omega_z = x;
	o->can_0x062_Imu3_rx = 1;
	o->can_0x062_Imu3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x062_omega_y(const can_obj_can2_h_t *o, int32_t *out) {
	assert(o);
	assert(out);
	int32_t rval = (int32_t)(o->can_0x062_Imu3.omega_y);
	*out = rval;
	return 0;
}

int encode_can_0x062_omega_y(can_obj_can2_h_t *o, int32_t in) {
	assert(o);
	o->can_0x062_Imu3.omega_y = in;
	return 0;
}

int decode_can_0x062_omega_z(const can_obj_can2_h_t *o, int32_t *out) {
	assert(o);
	assert(out);
	int32_t rval = (int32_t)(o->can_0x062_Imu3.omega_z);
	*out = rval;
	return 0;
}

int encode_can_0x062_omega_z(can_obj_can2_h_t *o, int32_t in) {
	assert(o);
	o->can_0x062_Imu3.omega_z = in;
	return 0;
}

int print_can_0x062_Imu3(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "omega_y = (wire: %.0f)\n", (double)(o->can_0x062_Imu3.omega_y)));
	r = print_helper(r, fprintf(output, "omega_z = (wire: %.0f)\n", (double)(o->can_0x062_Imu3.omega_z)));
	return r;
}

static int pack_can_0x063_Map(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* power: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x063_Map.power)) & 0xf;
	i |= x;
	/* regen: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x063_Map.regen)) & 0xf;
	x <<= 4; 
	i |= x;
	*data = (i);
	o->can_0x063_Map_tx = 1;
	return 1;
}

static int unpack_can_0x063_Map(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* power: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x063_Map.power = x;
	/* regen: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x063_Map.regen = x;
	o->can_0x063_Map_rx = 1;
	o->can_0x063_Map_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x063_power(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x063_Map.power);
	if ((rval >= 1) && (rval <= 12)) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x063_power(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x063_Map.power = 0;
	if (in < 1)
		return -1;
	if (in > 12)
		return -1;
	o->can_0x063_Map.power = in;
	return 0;
}

int decode_can_0x063_regen(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x063_Map.regen);
	if ((rval >= 1) && (rval <= 12)) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x063_regen(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x063_Map.regen = 0;
	if (in < 1)
		return -1;
	if (in > 12)
		return -1;
	o->can_0x063_Map.regen = in;
	return 0;
}

int print_can_0x063_Map(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "power = (wire: %.0f)\n", (double)(o->can_0x063_Map.power)));
	r = print_helper(r, fprintf(output, "regen = (wire: %.0f)\n", (double)(o->can_0x063_Map.regen)));
	return r;
}

static int pack_can_0x100_Temp1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* r_inv_temp_in: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.r_inv_temp_in)) & 0xffff;
	i |= x;
	/* r_inv_temp_out: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.r_inv_temp_out)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* l_inv_temp_in: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.l_inv_temp_in)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* l_inv_temp_out: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.l_inv_temp_out)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x100_Temp1_tx = 1;
	return 8;
}

static int unpack_can_0x100_Temp1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* r_inv_temp_in: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x100_Temp1.r_inv_temp_in = x;
	/* r_inv_temp_out: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x100_Temp1.r_inv_temp_out = x;
	/* l_inv_temp_in: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x100_Temp1.l_inv_temp_in = x;
	/* l_inv_temp_out: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x100_Temp1.l_inv_temp_out = x;
	o->can_0x100_Temp1_rx = 1;
	o->can_0x100_Temp1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x100_r_inv_temp_in(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.r_inv_temp_in);
	*out = rval;
	return 0;
}

int encode_can_0x100_r_inv_temp_in(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.r_inv_temp_in = in;
	return 0;
}

int decode_can_0x100_r_inv_temp_out(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.r_inv_temp_out);
	*out = rval;
	return 0;
}

int encode_can_0x100_r_inv_temp_out(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.r_inv_temp_out = in;
	return 0;
}

int decode_can_0x100_l_inv_temp_in(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.l_inv_temp_in);
	*out = rval;
	return 0;
}

int encode_can_0x100_l_inv_temp_in(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.l_inv_temp_in = in;
	return 0;
}

int decode_can_0x100_l_inv_temp_out(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.l_inv_temp_out);
	*out = rval;
	return 0;
}

int encode_can_0x100_l_inv_temp_out(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.l_inv_temp_out = in;
	return 0;
}

int print_can_0x100_Temp1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "r_inv_temp_in = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.r_inv_temp_in)));
	r = print_helper(r, fprintf(output, "r_inv_temp_out = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.r_inv_temp_out)));
	r = print_helper(r, fprintf(output, "l_inv_temp_in = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.l_inv_temp_in)));
	r = print_helper(r, fprintf(output, "l_inv_temp_out = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.l_inv_temp_out)));
	return r;
}

static int pack_can_0x101_Temp2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* r_mot_temp_in: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.r_mot_temp_in)) & 0xffff;
	i |= x;
	/* r_mot_temp_out: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.r_mot_temp_out)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* l_mot_temp_in: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.l_mot_temp_in)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* l_mot_temp_out: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.l_mot_temp_out)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x101_Temp2_tx = 1;
	return 8;
}

static int unpack_can_0x101_Temp2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* r_mot_temp_in: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x101_Temp2.r_mot_temp_in = x;
	/* r_mot_temp_out: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x101_Temp2.r_mot_temp_out = x;
	/* l_mot_temp_in: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x101_Temp2.l_mot_temp_in = x;
	/* l_mot_temp_out: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x101_Temp2.l_mot_temp_out = x;
	o->can_0x101_Temp2_rx = 1;
	o->can_0x101_Temp2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x101_r_mot_temp_in(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.r_mot_temp_in);
	*out = rval;
	return 0;
}

int encode_can_0x101_r_mot_temp_in(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.r_mot_temp_in = in;
	return 0;
}

int decode_can_0x101_r_mot_temp_out(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.r_mot_temp_out);
	*out = rval;
	return 0;
}

int encode_can_0x101_r_mot_temp_out(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.r_mot_temp_out = in;
	return 0;
}

int decode_can_0x101_l_mot_temp_in(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.l_mot_temp_in);
	*out = rval;
	return 0;
}

int encode_can_0x101_l_mot_temp_in(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.l_mot_temp_in = in;
	return 0;
}

int decode_can_0x101_l_mot_temp_out(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.l_mot_temp_out);
	*out = rval;
	return 0;
}

int encode_can_0x101_l_mot_temp_out(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.l_mot_temp_out = in;
	return 0;
}

int print_can_0x101_Temp2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "r_mot_temp_in = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.r_mot_temp_in)));
	r = print_helper(r, fprintf(output, "r_mot_temp_out = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.r_mot_temp_out)));
	r = print_helper(r, fprintf(output, "l_mot_temp_in = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.l_mot_temp_in)));
	r = print_helper(r, fprintf(output, "l_mot_temp_out = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.l_mot_temp_out)));
	return r;
}

static int pack_can_0x102_SuspFront(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* susp_fr: start-bit 0, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x102_SuspFront.susp_fr)) & 0x3ff;
	i |= x;
	/* susp_fl: start-bit 10, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x102_SuspFront.susp_fl)) & 0x3ff;
	x <<= 10; 
	i |= x;
	*data = (i);
	o->can_0x102_SuspFront_tx = 1;
	return 3;
}

static int unpack_can_0x102_SuspFront(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 3)
		return -1;
	/* susp_fr: start-bit 0, length 10, endianess intel, scaling 1, offset 0 */
	x = i & 0x3ff;
	o->can_0x102_SuspFront.susp_fr = x;
	/* susp_fl: start-bit 10, length 10, endianess intel, scaling 1, offset 0 */
	x = (i >> 10) & 0x3ff;
	o->can_0x102_SuspFront.susp_fl = x;
	o->can_0x102_SuspFront_rx = 1;
	o->can_0x102_SuspFront_time_stamp_rx = time_stamp;
	return 3;
}

int decode_can_0x102_susp_fr(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x102_SuspFront.susp_fr);
	*out = rval;
	return 0;
}

int encode_can_0x102_susp_fr(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x102_SuspFront.susp_fr = in;
	return 0;
}

int decode_can_0x102_susp_fl(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x102_SuspFront.susp_fl);
	*out = rval;
	return 0;
}

int encode_can_0x102_susp_fl(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x102_SuspFront.susp_fl = in;
	return 0;
}

int print_can_0x102_SuspFront(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "susp_fr = (wire: %.0f)\n", (double)(o->can_0x102_SuspFront.susp_fr)));
	r = print_helper(r, fprintf(output, "susp_fl = (wire: %.0f)\n", (double)(o->can_0x102_SuspFront.susp_fl)));
	return r;
}

static int pack_can_0x103_SuspRear(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* susp_rr: start-bit 0, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x103_SuspRear.susp_rr)) & 0x3ff;
	i |= x;
	/* susp_rl: start-bit 10, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x103_SuspRear.susp_rl)) & 0x3ff;
	x <<= 10; 
	i |= x;
	*data = (i);
	o->can_0x103_SuspRear_tx = 1;
	return 3;
}

static int unpack_can_0x103_SuspRear(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 3)
		return -1;
	/* susp_rr: start-bit 0, length 10, endianess intel, scaling 1, offset 0 */
	x = i & 0x3ff;
	o->can_0x103_SuspRear.susp_rr = x;
	/* susp_rl: start-bit 10, length 10, endianess intel, scaling 1, offset 0 */
	x = (i >> 10) & 0x3ff;
	o->can_0x103_SuspRear.susp_rl = x;
	o->can_0x103_SuspRear_rx = 1;
	o->can_0x103_SuspRear_time_stamp_rx = time_stamp;
	return 3;
}

int decode_can_0x103_susp_rr(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x103_SuspRear.susp_rr);
	*out = rval;
	return 0;
}

int encode_can_0x103_susp_rr(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x103_SuspRear.susp_rr = in;
	return 0;
}

int decode_can_0x103_susp_rl(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x103_SuspRear.susp_rl);
	*out = rval;
	return 0;
}

int encode_can_0x103_susp_rl(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x103_SuspRear.susp_rl = in;
	return 0;
}

int print_can_0x103_SuspRear(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "susp_rr = (wire: %.0f)\n", (double)(o->can_0x103_SuspRear.susp_rr)));
	r = print_helper(r, fprintf(output, "susp_rl = (wire: %.0f)\n", (double)(o->can_0x103_SuspRear.susp_rl)));
	return r;
}

static int pack_can_0x120_InvVolt(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* car_voltage: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x120_InvVolt.car_voltage)) & 0xffff;
	i |= x;
	*data = (i);
	o->can_0x120_InvVolt_tx = 1;
	return 4;
}

static int unpack_can_0x120_InvVolt(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 4)
		return -1;
	/* car_voltage: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x120_InvVolt.car_voltage = x;
	o->can_0x120_InvVolt_rx = 1;
	o->can_0x120_InvVolt_time_stamp_rx = time_stamp;
	return 4;
}

int decode_can_0x120_car_voltage(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x120_InvVolt.car_voltage);
	if (rval <= 600) {
		*out = rval;
		return 0;
	} else {
		*out = (uint16_t)0;
		return -1;
	}
}

int encode_can_0x120_car_voltage(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x120_InvVolt.car_voltage = 0;
	if (in > 600)
		return -1;
	o->can_0x120_InvVolt.car_voltage = in;
	return 0;
}

int print_can_0x120_InvVolt(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "car_voltage = (wire: %.0f)\n", (double)(o->can_0x120_InvVolt.car_voltage)));
	return r;
}

static int pack_can_0x130_Pcu(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* fan_speed: start-bit 1, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.fan_speed)) & 0x7f;
	x <<= 1; 
	i |= x;
	/* pump_speed: start-bit 9, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.pump_speed)) & 0x7f;
	x <<= 9; 
	i |= x;
	/* fan_enable: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.fan_enable)) & 0x1;
	i |= x;
	/* pump_enable: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.pump_enable)) & 0x1;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x130_Pcu_tx = 1;
	return 2;
}

static int unpack_can_0x130_Pcu(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 2)
		return -1;
	/* fan_speed: start-bit 1, length 7, endianess intel, scaling 1, offset 0 */
	x = (i >> 1) & 0x7f;
	o->can_0x130_Pcu.fan_speed = x;
	/* pump_speed: start-bit 9, length 7, endianess intel, scaling 1, offset 0 */
	x = (i >> 9) & 0x7f;
	o->can_0x130_Pcu.pump_speed = x;
	/* fan_enable: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->can_0x130_Pcu.fan_enable = x;
	/* pump_enable: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->can_0x130_Pcu.pump_enable = x;
	o->can_0x130_Pcu_rx = 1;
	o->can_0x130_Pcu_time_stamp_rx = time_stamp;
	return 2;
}

int decode_can_0x130_fan_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.fan_speed);
	*out = rval;
	return 0;
}

int encode_can_0x130_fan_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.fan_speed = in;
	return 0;
}

int decode_can_0x130_pump_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.pump_speed);
	*out = rval;
	return 0;
}

int encode_can_0x130_pump_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.pump_speed = in;
	return 0;
}

int decode_can_0x130_fan_enable(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.fan_enable);
	*out = rval;
	return 0;
}

int encode_can_0x130_fan_enable(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.fan_enable = in;
	return 0;
}

int decode_can_0x130_pump_enable(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.pump_enable);
	*out = rval;
	return 0;
}

int encode_can_0x130_pump_enable(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.pump_enable = in;
	return 0;
}

int print_can_0x130_Pcu(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "fan_speed = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.fan_speed)));
	r = print_helper(r, fprintf(output, "pump_speed = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.pump_speed)));
	r = print_helper(r, fprintf(output, "fan_enable = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.fan_enable)));
	r = print_helper(r, fprintf(output, "pump_enable = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.pump_enable)));
	return r;
}

static int pack_can_0x131_Calib(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* position: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x131_Calib.position)) & 0xff;
	i |= x;
	switch (o->can_0x131_Calib.position) {
	default:
		return -1;
	}
	*data = (i);
	o->can_0x131_Calib_tx = 1;
	return 1;
}

static int unpack_can_0x131_Calib(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* position: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x131_Calib.position = x;
	switch (o->can_0x131_Calib.position) {
	default:
		return -1;
	}
	o->can_0x131_Calib_rx = 1;
	o->can_0x131_Calib_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x131_position(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x131_Calib.position);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x131_position(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x131_Calib.position = 0;
	if (in > 1)
		return -1;
	o->can_0x131_Calib.position = in;
	return 0;
}

int print_can_0x131_Calib(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "position = (wire: %.0f)\n", (double)(o->can_0x131_Calib.position)));
	return r;
}

static int pack_can_0x3c2_Lem(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* current: start-bit 7, length 32, endianess motorola, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x3c2_Lem.current)) & 0xffffffff;
	x <<= 32; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x3c2_Lem_tx = 1;
	return 4;
}

static int unpack_can_0x3c2_Lem(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 4)
		return -1;
	/* current: start-bit 7, length 32, endianess motorola, scaling 1, offset 0 */
	x = (m >> 32) & 0xffffffff;
	o->can_0x3c2_Lem.current = x;
	o->can_0x3c2_Lem_rx = 1;
	o->can_0x3c2_Lem_time_stamp_rx = time_stamp;
	return 4;
}

int decode_can_0x3c2_current(const can_obj_can2_h_t *o, uint32_t *out) {
	assert(o);
	assert(out);
	uint32_t rval = (uint32_t)(o->can_0x3c2_Lem.current);
	*out = rval;
	return 0;
}

int encode_can_0x3c2_current(can_obj_can2_h_t *o, uint32_t in) {
	assert(o);
	o->can_0x3c2_Lem.current = in;
	return 0;
}

int print_can_0x3c2_Lem(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "current = (wire: %.0f)\n", (double)(o->can_0x3c2_Lem.current)));
	return r;
}

int unpack_message(can_obj_can2_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x053: return unpack_can_0x053_Driver(o, data, dlc, time_stamp);
	case 0x054: return unpack_can_0x054_Paddle(o, data, dlc, time_stamp);
	case 0x055: return unpack_can_0x055_BmsHv1(o, data, dlc, time_stamp);
	case 0x056: return unpack_can_0x056_BmsHv2(o, data, dlc, time_stamp);
	case 0x057: return unpack_can_0x057_BmsLv1(o, data, dlc, time_stamp);
	case 0x058: return unpack_can_0x058_BmsLv2(o, data, dlc, time_stamp);
	case 0x060: return unpack_can_0x060_Imu1(o, data, dlc, time_stamp);
	case 0x061: return unpack_can_0x061_Imu2(o, data, dlc, time_stamp);
	case 0x062: return unpack_can_0x062_Imu3(o, data, dlc, time_stamp);
	case 0x063: return unpack_can_0x063_Map(o, data, dlc, time_stamp);
	case 0x100: return unpack_can_0x100_Temp1(o, data, dlc, time_stamp);
	case 0x101: return unpack_can_0x101_Temp2(o, data, dlc, time_stamp);
	case 0x102: return unpack_can_0x102_SuspFront(o, data, dlc, time_stamp);
	case 0x103: return unpack_can_0x103_SuspRear(o, data, dlc, time_stamp);
	case 0x120: return unpack_can_0x120_InvVolt(o, data, dlc, time_stamp);
	case 0x130: return unpack_can_0x130_Pcu(o, data, dlc, time_stamp);
	case 0x131: return unpack_can_0x131_Calib(o, data, dlc, time_stamp);
	case 0x3c2: return unpack_can_0x3c2_Lem(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_can2_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x053: return pack_can_0x053_Driver(o, data);
	case 0x054: return pack_can_0x054_Paddle(o, data);
	case 0x055: return pack_can_0x055_BmsHv1(o, data);
	case 0x056: return pack_can_0x056_BmsHv2(o, data);
	case 0x057: return pack_can_0x057_BmsLv1(o, data);
	case 0x058: return pack_can_0x058_BmsLv2(o, data);
	case 0x060: return pack_can_0x060_Imu1(o, data);
	case 0x061: return pack_can_0x061_Imu2(o, data);
	case 0x062: return pack_can_0x062_Imu3(o, data);
	case 0x063: return pack_can_0x063_Map(o, data);
	case 0x100: return pack_can_0x100_Temp1(o, data);
	case 0x101: return pack_can_0x101_Temp2(o, data);
	case 0x102: return pack_can_0x102_SuspFront(o, data);
	case 0x103: return pack_can_0x103_SuspRear(o, data);
	case 0x120: return pack_can_0x120_InvVolt(o, data);
	case 0x130: return pack_can_0x130_Pcu(o, data);
	case 0x131: return pack_can_0x131_Calib(o, data);
	case 0x3c2: return pack_can_0x3c2_Lem(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_can2_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x053: return print_can_0x053_Driver(o, output);
	case 0x054: return print_can_0x054_Paddle(o, output);
	case 0x055: return print_can_0x055_BmsHv1(o, output);
	case 0x056: return print_can_0x056_BmsHv2(o, output);
	case 0x057: return print_can_0x057_BmsLv1(o, output);
	case 0x058: return print_can_0x058_BmsLv2(o, output);
	case 0x060: return print_can_0x060_Imu1(o, output);
	case 0x061: return print_can_0x061_Imu2(o, output);
	case 0x062: return print_can_0x062_Imu3(o, output);
	case 0x063: return print_can_0x063_Map(o, output);
	case 0x100: return print_can_0x100_Temp1(o, output);
	case 0x101: return print_can_0x101_Temp2(o, output);
	case 0x102: return print_can_0x102_SuspFront(o, output);
	case 0x103: return print_can_0x103_SuspRear(o, output);
	case 0x120: return print_can_0x120_InvVolt(o, output);
	case 0x130: return print_can_0x130_Pcu(o, output);
	case 0x131: return print_can_0x131_Calib(o, output);
	case 0x3c2: return print_can_0x3c2_Lem(o, output);
	default: break; 
	}
	return -1; 
}

